### ISSUE TITLE
Artifact Expired

### ISSUE THREAD

**Issue by brunoman4006** [Slackadays/FoliaToGo#2]
Error while accessnig the website https://nightly.link/Slackadays/FoliaToGo/workflows/folia/main/FoliaToGo

Error 404 – Not Found

GitHub produced an error for the download of artifact #1407089082.

Usually this means that the artifact has expired (>90 days).

Check on GitHub: https://github.com/Slackadays/FoliaToGo/suites/22681011464/artifacts/1407089082

**Comment by BridgerSilk** [comment]
having trouble with the same issue rn

**Comment by Slackadays** [comment]
Should be working again now!
